name: Deploy to EKS

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::920372990505:role/github-actions-cicd
  ECR_REPO_NAME: ecr-repository-dev
  EKS_CLUSTER_NAME: EKS-cluster-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push Docker Image
      run: |
        IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:latest"
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Ensure EBS CSI Driver is installed
      run: |
        if ! kubectl get csidriver ebs.csi.aws.com >/dev/null 2>&1; then
          echo "EBS CSI Driver not found. Installing..."
          helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          helm repo update
          helm upgrade --install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
            --namespace kube-system \
            --set controller.serviceAccount.create=false \
            --set controller.serviceAccount.name=ebs-csi-controller-sa \
            --set node.serviceAccount.name=ebs-csi-node-sa \
            --wait
        else
          echo "EBS CSI Driver is already installed."
        fi

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8/
